name: Render Map

on:
  push:
    paths:
      - "Station.json"
      - "Path.json"
  pull_request:
    paths:
      - "Station.json"
      - "Path.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'https://github.com/C1710/TrainCompany-tools.git'
          path: 'tools'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install matplotlib
        run: python -m pip install matplotlib
      - name: Render map
        run: python tools/plot.py
      - uses: actions/upload-artifact@v3
        with:
          name: map
          path: map_plot.svg